#!/bin/bash

# Copyright (C) 2007, 2008, 2009, 2012 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

. common.sh

if [ "$GENERATE_CACHE" = "yes" -a ! -d "$CACHE_DIR" ]; then
  mkdir -p "$CACHE_DIR"
fi

DPKG_ARCH=${ARCH:-`dpkg --print-architecture`}
CACHE_FILE="$CACHE_DIR/cache-${SUITE}-${DPKG_ARCH}.tar"

# If the target device is not a real block device we'll first losetup it.
# This is needed for file disks.
if [ ! -b $blockdev ]; then
  ORIGINAL_BLOCKDEV=$blockdev
  blockdev=$(losetup --show -f $blockdev)
  CLEANUP+=("losetup -d $blockdev")
fi

# Check is there are more than 2 empty OSP_*_SIZE.
if [ -z "$OSP_ROOT_SIZE" -a -z "$OSP_SWAP_SIZE" ]; then
  echo "Only one of root_size and swap_size can be empty."
  exit 1
fi

if [ -z "$OSP_ROOT_SIZE" -a -z "$OSP_VAR_SIZE" ]; then
  echo "Only one of root_size and var_size can be empty."
  exit 1
fi

if [ -z "$OSP_SWAP_SIZE" -a -z "$OSP_VAR_SIZE" ]; then
  echo "Only one of swap_size and var_size can be empty."
  exit 1
fi

# Find device size.
DEVICE_SIZE=$(blockdev --getsize64 $blockdev)

# Compute the missing size.
if [ -z "OSP_ROOT_SIZE" ]; then
    OSP_ROOT_SIZE=$((DEVICE_SIZE/ONE_MIB-SWAP_SIZE-VAR_SIZE))
elif [ -z "OSP_SWAP_SIZE" ]; then
    OSP_SWAP_SIZE=$((DEVICE_SIZE/ONE_MIB-ROOT_SIZE-VAR_SIZE))
elif [ -z "OSP_VAR_SIZE" ]; then
    OSP_VAR_SIZE=$((DEVICE_SIZE/ONE_MIB-ROOT_SIZE-SWAP_SIZE))
fi

# Check minimal sizes
if [ -n "$OSP_ROOT_SIZE" ]; then
  if [ "$OSP_ROOT_SIZE" -lt "$ROOT_MIN_SIZE" ]; then
    echo "root FS size (${OSP_ROOT_SIZE}MiB) must be greater than ${ROOT_MIN_SIZE}MiB."
    exit 1
  fi
fi

if [ -n "$OSP_SWAP_SIZE" ]; then
  if [ "$OSP_SWAP_SIZE" -lt "$SWAP_MIN_SIZE" ]; then
    echo "swap size (${OSP_SWAP_SIZE}MiB) must be greater than ${SWAP_MIN_SIZE}MiB."
    exit 1
  fi
fi

if [ -n "$OSP_VAR_SIZE" ]; then
  if [ "$OSP_VAR_SIZE" -lt "$VAR_MIN_SIZE" ]; then
    echo "var FS size (${OSP_VAR_SIZE}MiB) must be greater than ${VAR_MIN_SIZE}MiB."
    exit 1
  fi
fi

# Check minimum disk size.

# PARTITION_ALIGNMENT is in sectors, converting it to bytes.
PA_BYTES=$((PARTITION_ALIGNMENT*512))
declare -ri MIN_DEV_SIZE=$((PA_BYTES+(OSP_ROOT_FS+OSP_SWAP_SIZE+OSP_VAR_SIZE)*ONE_MIB))

if [ "$DEVICE_SIZE" -lt $MIN_DEV_SIZE ]; then
  echo "Device size is too small ($((DEVICE_SIZE/ONE_MIB))MiB)" 1>&2
  echo "Required size is at least $((MIN_DEV_SIZE/ONE_MIB))MiB" 1>&2
  exit 1
fi

if [ "$PARTITION_STYLE" = "none" ]; then
  filesystem_dev=$blockdev
elif [ "$PARTITION_STYLE" = "msdos" ]; then
  # Create one big partition, and make it bootable
  format_disk0 $blockdev
  eval $(map_disk0 $blockdev)
  CLEANUP+=("unmap_disk0 $blockdev")
elif [ "$PARTITION_STYLE" = "gpt" ]; then
    # Check if root_path is set to /dev/vda2 (or /dev/xvda2 for xen)
    echo "gpt label is not supported yet."
    exit 1
else
  echo "Unknown partition style $PARTITION_STYLE" 1>&2
  exit 1
fi

# Prepare failesystems
mkfs.$OSP_ROOT_FS $rootdev
root_uuid=$($VOL_ID $rootdev )

mkswap $swapdev
swap_uuid=$($VOL_ID $swapdev )

mkfs.$OSP_VAR_FS $vardev
var_uuid=$($VOL_ID $vardev )

# Mount filesystems
TMPDIR=`mktemp -d` || exit 1
CLEANUP+=("rmdir $TMPDIR")

mount $rootdev $TMPDIR
CLEANUP+=("umount $TMPDIR")

mkdir $TMPDIR/var

mount $vardev $TMPDIR/var
CLEAN_CACHE+=("umount $TMPDIR/var")

# remove the cache file if it's old (> 2 weeks) and writable by the owner (the
# default due to the standard umask)
if [ "$CLEAN_CACHE" -a -d "$CACHE_DIR" ]; then
  find "$CACHE_DIR" -name 'cache-*.tar' -type f \
    -daystart -mtime "+${CLEAN_CACHE}" -print0 | \
    xargs -r0 rm -f
fi

if [ -f "$CACHE_FILE" ]; then
  tar xf "$CACHE_FILE" -C $TMPDIR
else
  if [ "$PROXY" ]; then
    export http_proxy="$PROXY"
    export https_proxy="$PROXY"
  fi
  # INCLUDE will be empty if EXTRA_PKGS is null/empty, otherwise we
  # build the full parameter format from it
  INCLUDE=${EXTRA_PKGS:+"--include=$EXTRA_PKGS"}
  COMP=${COMPONENTS:+"--components=$COMPONENTS"}
  debootstrap \
    --arch "$DPKG_ARCH" \
    $INCLUDE \
    $COMP \
    "$SUITE" $TMPDIR $MIRROR

  # remove the downloaded debs, as they are no longer needed
  find "$TMPDIR/var/cache/apt/archives" -type f -name '*.deb' -print0 | \
    xargs -r0 rm -f

  # remove the persistent-net rules, otherwise it will remember the node's
  # interfaces as eth0, eth1, ...
  rm -f "$TMPDIR/etc/udev/rules.d/z25_persistent-net.rules"

  if [ "$GENERATE_CACHE" = "yes" ]; then
    TMP_CACHE=`mktemp "${CACHE_FILE}.XXXXXX"`
    tar cf "$TMP_CACHE" -C $TMPDIR .
    mv -f "$TMP_CACHE" "$CACHE_FILE"
  fi
fi

# reset the root password
chroot $TMPDIR passwd -d root

cp -p /etc/hosts $TMPDIR/etc/hosts
cp -p /etc/resolv.conf $TMPDIR/etc/resolv.conf
echo $instance > $TMPDIR/etc/hostname
echo $instance > $TMPDIR/etc/mailname

cat > $TMPDIR/etc/fstab <<EOF
# /etc/fstab: static file system information.
#
# <file system>   <mount point>   <type>  <options>       <dump>  <pass>
UUID=$root_uuid   /               $OSP_ROOT_FS    defaults        0       1
UUID=$swap_uuid   swap            swap    defaults        0       0
UUID=$var_uuid    /var            $OSP_VAR_FS    defaults        0       0
proc              /proc           proc    defaults        0       0
EOF

cat > $TMPDIR/etc/network/interfaces <<EOF
auto lo
iface lo inet loopback
EOF

# for kvm, we should only activate a serial console if the
# 'serial_console' parameter is set; for xen-pvm though, we should
# always define a serial console
SERIAL_PORT=""
if [ "$INSTANCE_HV_serial_console" = "True" ]; then
  SERIAL_PORT="ttyS0"
elif [ "$HYPERVISOR" = "xen-pvm" ]; then
  SERIAL_PORT="hvc0"
fi

if [ -n "$SERIAL_PORT" ]; then
  if [ -e $TMPDIR/etc/inittab ]; then
    # debian
    echo "T0:23:respawn:/sbin/getty $SERIAL_PORT 38400" >> $TMPDIR/etc/inittab
  elif [ -e $TMPDIR/etc/init ]; then
    # ubuntu (eg. karmic)
    cat > $TMPDIR/etc/init/${SERIAL_PORT}.conf <<EOF
start on stopped rc RUNLEVEL=[2345]
stop on runlevel [!2345]

respawn
exec /sbin/getty -8 38400 $SERIAL_PORT
EOF
  elif [ -e $TMPDIR/etc/event.d ]; then
    # ubuntu (eg. intrepid)
    cat > $TMPDIR/etc/event.d/${SERIAL_PORT}.conf <<EOF
start on stopped rc2
start on stopped rc3
start on stopped rc4
start on stopped rc5

stop on runlevel 0
stop on runlevel 1
stop on runlevel 6

respawn
exec /sbin/getty 38400 ${SERIAL_PORT}
EOF
  fi
fi

RUN_PARTS=`which run-parts`

if [ -n "$RUN_PARTS" -a -n "$CUSTOMIZE_DIR" -a -d "$CUSTOMIZE_DIR" ]; then
  TARGET=$TMPDIR
  BLOCKDEV=$blockdev
  FSYSDEV=$filesystem_dev
  export TARGET SUITE ARCH PARTITION_STYLE EXTRA_PKGS BLOCKDEV FSYSDEV
  $RUN_PARTS $CUSTOMIZE_DIR
fi

# execute cleanups
cleanup
trap - EXIT

exit 0
