#!/bin/bash

# Copyright (C) 2007, 2008, 2009 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

MKFS=$(which mkfs)

# Check if each OSP_*_FS is valid.
if [ ! -x "$MKFS.$OSP_ROOT_FS" ]; then
    echo "Invalid root_fs: the command $MKFS.$OSP_ROOT_FS does not exist."
    exit 1
fi

if [ ! -x "$MKFS.$OSP_VAR_FS" ]; then
    echo "Invalid var_fs: the command $MKFS.$OSP_VAR_FS does not exist."
    exit 1
fi

#check_empty_sizes

#check_minimal_sizes

exit 0

